version: "3"
services: 
  app:
    build: 
      context: .
    image: app1:latest
    environment: 
      - SECRET=TXgKIXx6UHq4vHMfWoQ8H7JB0ut6gsBrwH0BaaHprDXEJ9COLC81sDz1z4ZXWaA23gph7CjSiLwkPVCsmXjhvECiV9hCAE1o4n8VOJixr1VR95cy6sPWOCe6UZNKW4eJeCzPIuSMQ5cZXAt9PLBCG77jFBJIYOIvjHF9IwwkghebHwKL16vtjJUoPKabt1YbC03NvJ3noKflIqTlxTObn7LcGPTaG7qWShkf7dnrAA7qg5nTgxOUfaZ0FB6AQdI0
      - DB_PORT=15432
      - API_SETTING=development
      - FLASK_APP="app.py"
      - SERVER_HOST="0.0.0.0"
      - SERVER_PORT=5000
      - SQLITE_URI=sqlite:///data.db
      - SQLITE_FILE=data.db
      - POSTGRES_URL=app1-postgres:15432
      - POSTGRES_PW=Postgres2019!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes: 
      - ./:/app/
    ports: 
      - 5000:5000
    depends_on:
      - app1-postgres
    command: python app/code/app.py
  
  app1-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - data_app1db:/var/lib/postgresql/data

volumes:
  ? data_app1db