version: "3"
services: 
  app:
    depends_on:
      - app1-postgres
    build: 
      context: .
    image: app1:latest
    environment: 
      - SECRET=TXgKIXx6UHq4vHMfWoQ8H7JB0ut6gsBrwH0BaaHprDXEJ9COLC81sDz1z4ZXWaA23gph7CjSiLwkPVCsmXjhvECiV9hCAE1o4n8VOJixr1VR95cy6sPWOCe6UZNKW4eJeCzPIuSMQ5cZXAt9PLBCG77jFBJIYOIvjHF9IwwkghebHwKL16vtjJUoPKabt1YbC03NvJ3noKflIqTlxTObn7LcGPTaG7qWShkf7dnrAA7qg5nTgxOUfaZ0FB6AQdI0
      - DB_PORT=15432
      - DATABASE_URL=app1-postgres:/app1
      - API_SETTING=development
      - FLASK_APP="app.py"
      - POSTGRES_PASSWORD=Postgres2019!
      - SERVER_HOST="0.0.0.0"
      - SERVER_PORT=5000
    volumes: 
      - ./code:/app/code
    ports: 
      - 5000:5000
    command: python app/code/test.py
    command: python app/code/app.py
    networks:
      - postgres-compose-network
  
  app1-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - /home/volumes_study/app1db:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge

    
