version: "3"
services: 
  app:
    build: 
      context: .
    image: app1:latest
    environment: 
      - SECRET=secretHashCrazyImpossibleToGuessOrBreak
    volumes: 
      - ./code:/app/code
    ports: 
      - 5000:5000
    command: python app/code/app.py
    
